### ISSUE TITLE
Unable to download QR code when using an Android device

### ISSUE THREAD

**Issue by logesixas96** [logesixas96/QR-Tech-Host#17]
These will be the domain for web part of the system:

https://itp-qr-system.web.app/#/
https://itp-qr-system.firebaseapp.com/#/

Everything is good. The only additional issue will be access from mobile browser, which unable to download QR image. Others are fine. Do raise any issue if found.

**Comment by kshorenicholas** [comment]
> These will be the domain for web part of the system:
> 
> https://itp-qr-system.web.app/#/
> https://itp-qr-system.firebaseapp.com/#/
> 
> Everything is good. The only additional issue will be access from mobile browser, which unable to download QR image. Others are fine. Do raise any issue if found.

What is the difference between the two links?

**Comment by logesixas96** [comment]
Both are the same generated by firebase host as an alternative for one
another

**Comment by kshorenicholas** [comment]
Noted

**Comment by kshorenicholas** [comment]
Simple sol

> Everything is good. The only additional issue will be access from mobile browser, which unable to download QR image. Others are fine. Do raise any issue if found.

Although it is vital that we make it possible for the user to download the QR code, a simple solution for now would be to just have the user to screenshot the QR Code. But the only (minor) issue there being the resolution of the screenshot.

**Comment by logesixas96** [comment]
True. Furthermore, it requires to deploy the web build to the firebase hosting for each and every testing so that it could be tested  on mobile browser. Screenshot would be the simple solution as you mentioned for now.
