### ISSUE TITLE
Licensing of application

### ISSUE THREAD

**Issue by kshorenicholas** [logesixas96/QR-Tech-Host#19]
I would suggest we add a license to the application we have written. Personally, I would prefer [GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) as it ensures that future iterations and forks of the project to also remain open-source. 

@logesixas96 your opinion please?

**Comment by logesixas96** [comment]
I think it is good to add license unless we are going to keep the repo private. We may stick with GPLv2 license.
