### ISSUE TITLE
Email address verification

### ISSUE THREAD

**Issue by logesixas96** [logesixas96/QR-Tech-Host#21]
Do you think we should let the users to verify their email address in order to activate their account? This could avoid abuse of multiple accounts by each user.

**Comment by kshorenicholas** [comment]
Relevant documentation [here](https://firebase.google.com/docs/auth/flutter/manage-users#verify-email)

**Comment by kshorenicholas** [comment]
I have opened a branch for this issue

**Comment by logesixas96** [comment]
I had the implementation of email verification during the beginning phase of the development. It did work, but I did not continue as I thought of keeping that as an optional function at the end of project phase. I'll work on it.

**Comment by kshorenicholas** [comment]
Noted
