### ISSUE TITLE
Zooming in/out does not work as expected

### ISSUE THREAD

**Issue by kshorenicholas** [logesixas96/QR-Tech-Host#24]
Zooming in/out on the webpage creates whitespace on the borders of the browser surrounding the webpage. It seems to be render the web page as an image instead, but to be honest we still don't know the underlying cause.

**Comment by kshorenicholas** [comment]
I can fix this by today/tomorrow..not too hard

**Comment by logesixas96** [comment]
Noted. Do let me know if u couldn't deploy the web build to Firebase Host.

**Comment by kshorenicholas** [comment]
There is a weird issue. Running the app in debug mode on chrome shows me no issue but the website has the zoom problem. Could you check if the same happens on your side?

**Comment by kshorenicholas** [comment]
@logesixas96  could you try rendering the webpage using html instead of canvaskit? Some say it could work

**Comment by logesixas96** [comment]
> @logesixas96 could you try rendering the webpage using html instead of canvaskit? Some say it could work

Yes, it does work. However, the UI render quality is a downgrade compared to canvaskit in terms of fonts, appbar, colour etc. An alternative would be disabling the zoom in/ out for the web. What do you think? @kshorenicholas

**Comment by kshorenicholas** [comment]
Zoomin in/out would be a critical component for the end users especially for those with visual difficulties and thus will have to be in the app. I will test out the HTML renderer locally and check if there are any other workarounds. Especially if you say that it is visually not on par with the CanvasKit renderer.

**Comment by logesixas96** [comment]
@kshorenicholas I think it would be better to use HTML renderer as the difference is not much visible compared to Canvaskit.

**Comment by kshorenicholas** [comment]
After we switch to the HTML renderer, we will also have to do some performance testing to improve the user experience.

**Comment by kshorenicholas** [comment]
@logesixas96 Zooming in and out now works properly with the HTML renderer as compared to the canvaskit renderer. Performance improvements up next
