### ISSUE TITLE
Download QR Image to Android device

### ISSUE THREAD

**Issue by logesixas96** [logesixas96/QR-Tech-Host#8]
-I have updated to the most recent codes (merged your debugging of other screens too).
-Added attendancelist.dart & qrhistory.dart screens (needs debugging).

The final problem im facing is that the generated QR can only be downloaded through PC/laptop browsers. Im still searching for a way to make the users able to download from mobile browsers too.

**Comment by kshorenicholas** [comment]
What is the current issue with the attendancelist and qrhistory?

**Comment by kshorenicholas** [comment]
for the second issue refer here instead --> #9
